#!/bin/bash
#
#Busside arvutamine
echo -n "Sisesta grupi suurus: "
read suurus
echo -n "Sisesta kohtade arv bussis: "
read kohad

taidetud=`expr $suurus / $kohad`
echo "Läheb vaja $taidetud bussi"

mahajaanud=`expr $suurus - $taidetud \* $kohad`
echo "Mahajäänud inimesi on $mahajaanud"

