#!/bin/bash
#
echo -n "Sisesta täisarv: "
read numbrid
if [ $numbrid -lt 0 ]; then
	numbrid=$(($numbrid * -1)) # Kui numbrid on negatiived, muudab positiivseks
fi
echo -n "Arvu $numbrid numbrite summa on "
summa=0 # Numbrite arvutus
while [ $numbrid -gt 0 ]
do
	arv=$(($numbrid % 10))
	numbrid=$(($numbrid / 10))
	summa=$(($summa + $arv))
done
echo $summa
