#!/bin/bash
#
echo -n "Sisesta ridade arv: "
read rida
echo -n "Sisesta tärnide arv reas: "
read tarn
for (( i = 1; i <= $rida; i++ )) # Väline for tsükkel, mitu rida tuleb
do
	echo -n "$i. "
	for (( j = 1; j <= $tarn; j++ )) # Sisemine for tsükkel, mitu tärni tuleb
	do
		echo -n "* "
	done
echo "" # Prindib järgmise rea
done
