#!/bin/bash
#
# kasutaja tervitus
#
# skripti algus
#
# echo "Tere User!"
echo -n "Tere " # väljasta ilma reavahetuseta Tere
echo -n `whoami | cut -c1 | tr [:lower:] [:upper:]` # lõika esimene täht ja muuda suureks
echo -n `whoami | cut -c2-` # lõika kõik tähed alates 2-st
echo "!"
#
# skriptilõpp
